export const services=[
    {
      id:1,
      work:'branding',
      image:'/services/branding.jpg'
    },
    {
      id:2,
      work:'graphic designing',
      image:'/services/graphicdesign.jpg'
    },
    {
      id:3,
      work : 'social media ',
      image:'/services/socialmedia.jpg'
    },
    {
      id:4,
      work : 'website development',
      image:'/services/webdev.jpg'
    },
    {
      id:5,
      work : 'website design',
      image:'/services/webdesign.jpg'
    },
    {
      id:6,
      work : 'ui/ux',
      image:'/services/uiux.jpg'
    }
  ]



export const clients = [
  {
    id:1,
    name:'bella',
    image:'/client/bella.png'
  },
  {
    id:2,
    name:'hyphen',
    image:'/client/hyphen.png'
  },
  {
    id:3,
    name:'etos',
    image:'/client/etos.png'
  },
  {
    id:4,
    name:'alankit',
    image:'/client/alankit.png'
  },
  {
    id:5,
    name:'cartoon network',
    image:'/client/cartoon.png'
  },
  {
    id:6,
    name:'pogo',
    image:'/client/pogo.png'
  },
  {
    id:7,
    name:'prints publications',
    image:'/client/prints.jpg'
  },
  {
    id:8,
    name:'denova',
    image:'/client/denova.png'
  },
  {
    id:9,
    name:'spize',
    image:'/client/spize.jpeg'
  },
  {
    id:10,
    name:'brandpiper',
    image:'/logo/image3.png'
  },
  {
    id:11,
    name:'Park',
    image:'/client/park.jpg'
  },
  {
    id:12,
    name:'Prints',
    image:'/prints/image8.jpg'
  },
  {
    id:13,
    name:'Logo',
    image:'/client/logo.jpg'
  },
  
]

export const clientcontent=[
  {
    cid:1,
    name:'bella',
    image:'/client/bella/image1.png'
  },
  {
    cid:1,
    name:'bella',
    image:'/client/bella/image2.png'
  },
  {
    cid:1,
    name:'bella',
    image:'/client/bella/gif1.gif'
  },
  {
    cid:1,
    name:'bella',
    image:'/client/bella/gif2.gif'
  },
  {
    cid:1,
    name:'bella',
    image:'/client/bella/gif3.gif'
  },
  {
    cid:2,
    name:'hyphen',
    image:'/client/hyphen/image1.jpeg'
  },
  {
    cid:2,
    name:'hyphen',
    image:'/client/hyphen/image2.jpeg'
  },
  {
    cid:2,
    name:'hyphen',
    image:'/client/hyphen/video1.mp4'
  },
  {
    cid:2,
    name:'hyphen',
    image:'/client/hyphen/video2.mp4'
  },
  {
    cid:2,
    name:'hyphen',
    image:'/client/hyphen/video3.mp4'
  },
  {
    cid:2,
    name:'hyphen',
    image:'/client/hyphen/video4.mp4'
  },

  {
    cid:3,
    name:'etos',
    image :'/client/etos/image1.png'
  },

  {
    cid:3,
    name:'etos',
    image :'/client/etos/image2.jpg'
  },

  {
    cid:3,
    name:'etos',
    image :'/client/etos/video1.mp4'
  },

  //alankiit
  {
    cid:4,
    name:'alankit',
    image:'/client/alankit/image1.jpg'
  },
  {
    cid:4,
    name:'alankit',
    image:'/client/alankit/image2.jpg'
  },
  {
    cid:4,
    name:'alankit',
    image:'/client/alankit/video1.mp4'
  },
  {
    cid:4,
    name:'alankit',
    image:'/client/alankit/video2.mp4'
  },
  {
    cid:5,
    name:'cartoon network',
    image:'/client/cartoon/image1.png'
  },
  {
    cid:5,
    name:'cartoon network',
    image:'/client/cartoon/image2.jpg'
  },
  {
    cid:5,
    name:'cartoon network',
    image:'/client/cartoon/image4.png'
  },
  {
    cid:5,
    name:'cartoon network',
    image:'/client/cartoon/image3.jpg'
  },
  {
    cid:6,
    name:'pogo',
    image:'/client/pogo/image1.jpg'
  },
  {
    cid:6,
    name:'pogo',
    image:'/client/pogo/image2.jpg'
  },
  {
    cid:6,
    name:'pogo',
    image:'/client/pogo/image3.jpg'
  },
  {
    cid:6,
    name:'pogo',
    image:'/client/pogo/video1.mp4'
  },
  {
    cid:7,
    name:'prints',
    image:'/client/prints/print1.png'
  },
  {
    cid:7,
    name:'prints',
    image:'/client/prints/print2.png'
  },
  {
    cid:7,
    name:'prints',
    image:'/client/prints/print3.png'
  },
  {
    cid:8,
    name:'denova',
    image:'/denova/image1.jpg'
  },
  {
    cid:8,
    name:'denova',
    image:'/denova/image2.png'
  },
  {
    cid:8,
    name:'denova',
    image:'/denova/image3.jpeg'
  },
  {
    cid:8,
    name:'denova',
    image:'/denova/video1.mp4'
  },
  {
    cid:8,
    name:'denova',
    image:'/denova/video2.mp4'
  },
  {
    cid:9,
    name:'spize',
    image:'/spize/video1.mp4'
  },
  {
    cid:9,
    name:'spize',
    image:'/spize/video2.mp4'
  },
  {
    cid:9,
    name:'spize',
    image:'/spize/image1.jpg'
  },
  {
    cid:10,
    name:'brandpipers',
    image:'/brandpipers/image1.png'
  },
  {
    cid:10,
    name:'brandpipers',
    image:'/brandpipers/image2.jpg'
  },
  {
    cid:10,
    name:'brandpipers',
    image:'/brandpipers/image3.jpg'
  },
  {
    cid:10,
    name:'brandpipers',
    image:'/brandpipers/image4.png'
  },
  {
    cid:10,
    name:'brandpipers',
    image:'/brandpipers/image5.gif'
  },
  {
    cid:10,
    name:'brandpipers',
    image:'/brandpipers/video1.mp4'
  },
  {
    cid:11,
    name:'park',
    image:'/park/image1.png'
  },
  {
    cid:11,
    name:'park',
    image:'/park/image2.png'
  },
  {
    cid:11,
    name:'park',
    image:'/park/image3.jpeg'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image1.jpeg'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image2.jpeg'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image3.png'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image4.png'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image5.jpeg'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image6.jpeg'
  },
  {
    cid:12,
    name:'print',
    image:'/prints/image7.png'
  },
  {
    cid:13,
    name:'logo',
    image:'/logo/image1.png'
  },
  {
    cid:13,
    name:'logo',
    image:'/logo/image2.jpeg'
  },
  {
    cid:13,
    name:'logo',
    image:'/logo/image4.jpeg'
  },

  
]
